### ISSUE TITLE
image disortion in article on mobile

### ISSUE THREAD

**Issue by vincerossi** [Smithsonian/dpo-voyager#107]
Using this model: https://3d.si.edu/object/3d/unknown-burial:297ef043-dfe2-4a68-978a-a570b2c3ab18 

upon clicking annotation #5, on mobile, the image in the article is distorted (Google Pixel 5a, Andorud 11, chrome 95.04638.74)
![Screenshot_20211117-094853](https://user-images.githubusercontent.com/42784444/142225516-6c7cd9b9-aded-442f-a7ea-de09fd3c89f9.png) 

it should look like this (desktop macbook air):
<img width="1440" alt="Screen Shot 2021-11-17 at 9 48 47 AM" src="https://user-images.githubusercontent.com/42784444/142225450-89c2c4ff-c4ce-4bdb-80a4-693a9e01e21e.png">

**Comment by gjcope** [comment]
This issue is due to bad image formatting in the article html. It looks like in several Jamestown scene articles the html was opened and manually edited. I don't think there isn't really a good way we can stop this from happening. I have fixed all instances of this in the Jamestown scenes, but it could exist elsewhere.
