### ISSUE TITLE
Hyperlinks in Annotations

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#176]
Is is possible to make lead text for annotations an active URL link?

**Comment by gjcope** [comment]
Yes, this shouldn't be an issue. We can support a selection of html tags, like link, bold, italic.

**Comment by smoore4moma** [comment]
Here is another potential idea.  It is a 3D viewer that the Smithsonian
created to view their objects in 3D.  Here is an example:

https://3d-api.si.edu/voyager/3d_package:341c96cd-f967-4540-8ed1-d3fc56d31f12

I set this up a few years ago with a 3D model of Starry Night, but I think
it needs to be done with a sculpture like She-Goat
<https://tms.moma.org/#/detail/81670>.

https://github.com/Smithsonian/dpo-voyager

Just a thought.

Steve

Steven MOORE

Developer & Database Administrator

Department of Information Technology


Change is Modern. Discover something new every day at MoMA
<http://moma.org/>.


The Museum of Modern Art

11 West 53 Street

New York, NY 10019
212.708.9706
813.240.0587

**Comment by smoore4moma** [comment]
Deleted my previous comment.  Internally, we have a discussion going around about a "Tech Showcase" - something we do about once a year.  Among ML, AI, and other examples, I suggested to my colleagues that we try this project, meaning show it to a group of other museum staff so that they know this exists for potential use cases.  Steve

**Comment by gjcope** [comment]
Added this feature in v0.24.0. through support for bold, italic, and link HTML tags in annotations.
