### ISSUE TITLE
The changes to background, floor, and grid colors are not updated in the JSON

### ISSUE THREAD

**Issue by oM4Uo** [Smithsonian/dpo-voyager#267]
The changes to background, floor, and grid colors are not recorded in the downloaded JSON using Story. Tested on local build from master and RC-40 branch and online Story standalone. The RGB parameters in the final scene JSON file are the default ones

**Comment by gjcope** [comment]
Hi @oM4Uo , are you capturing the scene settings before saving ('Capture' button under 'Capture' task)? It seems to be working for me. It's not an ideal workflow, but we separated capturing scene settings from everything else because we had a lot of users adding content and then unintentionally overwriting their model pose when saving. It's definitely something we could make more intuitive.

**Comment by gjcope** [comment]
No worries. If you have any suggestions on how to make this piece more user friendly please let us know!

**Comment by oM4Uo** [comment]
@gjcope a possibility could be to add under each section of backgroud, floor and grid 3 bottons: Save, Reset, Default 
maybe something like this

<img src=https://github.com/Smithsonian/dpo-voyager/assets/166654036/bb5447b2-c99b-49f8-8443-1655b0f49a76 width="250">


- Save: apply changes of the related section (backgroud section in the image)
- Reset: If available, set style and color values to those loaded from the original scene JSON file; otherwise, set them to the 'Smithsonian' ones
- Default: set style and colors values to the "Smithsonian" ones

I don't know how hard it is to make these changes, but maybe only the save button is enough
