### ISSUE TITLE
Model not loading in Firefox Browser

### ISSUE THREAD

**Issue by ericpugh** [Smithsonian/dpo-voyager#282]
I'm having an issue with loading a [specific 3D Model](https://3d.si.edu/object/3d/ritual-wine-ewer-gong-masks-taotie-dragons-and-real-animals:d8c646aa-4ebc-11ea-b77f-2e728ce88125) in Firefox 126.0.1 (64-bit). (Works as expected in Chrome and Edge).

Other models are loading without an issue, but with this specific object I'm getting a CORS error for several .glb files.

Console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.3d-api.si.edu/d8c646aa-4ebc-11ea-b77f-2e728ce88125/f1961_33-part_01-laser-ortery_texture-20k-512-thumb.glb. (Reason: CORS request did not succeed). Status code: (null).
```

Screenshot:

![screenshot-ff-bug](https://github.com/Smithsonian/dpo-voyager/assets/1176767/84e5f644-d9b8-4237-93c8-752e8a31550f)

**Comment by gjcope** [comment]
Hi @ericpugh - Is this still happening for you? I just tried it in Firefox and it seems fine for me. If so, this might be something for @andrewgunther to comment on.... we are testing 3d delivery via cdn with this model, so that would be the main difference. If it's still happening, can you also try https://3d.si.edu/object/3d/1903-wright-flyer:d8c62e5e-4ebc-11ea-b77f-2e728ce88125 ? This is the other model on the cdn.

**Comment by ericpugh** [comment]
No, it loads normally now. Perhaps an issue with some cached asset.
