### ISSUE TITLE
Annotation pointing to a deleted article opens the article picker

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#51]
If you delete an article that an annotation is pointing to, that annotations “Read more” link takes you to the article picker. While this is a reasonable fall back for an article that does not exist, ideally the “Read more” text would not show up if the linked article was missing. Though it is also reasonable to assume the responsibility for removing the annotation link is on the human author and not the tool...

**Comment by gjcope** [comment]
Added functionality to remove 'read more' when an article is deleted in Story. However, if the html asset for an article is deleted via the media manager (or is missing in some other way) the link will remain and you will get an "Article not found" error. I think this is the appropriate action since it will signal an actual missing asset that needs to be resolved.

**Comment by gjcope** [comment]
Added in #104
