### ISSUE TITLE
Pixelated shadow on floor from model

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#8]
Model viewed in Voyager v0.7.5
Scene created using web-multi recipe and web-thumb recipe

This seems to be related to the `radius` value of the floor. With smaller floor `radius` floor values corresponding to a more pixelated floor (making this assumption after reviewing 5 scenes).

![image](https://user-images.githubusercontent.com/49207360/73956023-51be9d00-48d2-11ea-9e89-ecdee1de3d0a.png)
Floor radius: 5.8

![image](https://user-images.githubusercontent.com/49207360/73956046-5be09b80-48d2-11ea-9528-f303ff0146b6.png)
Floor radius: 1.7

![image](https://user-images.githubusercontent.com/49207360/73956076-6733c700-48d2-11ea-88ca-735a4fb4919b.png)
Floor radius: 230

![image](https://user-images.githubusercontent.com/49207360/73956107-76b31000-48d2-11ea-9b36-965bdee2bf00.png)
Floor radius: 50

**Comment by framefactory** [comment]
You need to adjust the shadow size and resolution in the settings of the corresponding light sources. Also, if an object is very large or small, the positions of the lights need to be adjusted in order to throw the shadow properly. The MVP doesn't do this automatically. More automatic setup was planned for v1.0.

**Comment by gjcope** [comment]
Fixed in v0.28.0
