### ISSUE TITLE
Annotations don't update when model is reposed

### ISSUE THREAD

**Issue by gjcope** [Smithsonian/dpo-voyager#84]
In Voyager Story, if the model is rotated in "Pose" mode, the annotations do not seem to move with it.

**Comment by ThibaultGuillaumont** [comment]
Also, when model is rescaled by changing the units (meter -> mm), the annotations are not moving.

On a side note about scaling, when we import models from Blender or Scaniverse, the Item Unit default unit should be (m) instead of (mm). Hence the trouble with annotations when the user realize it too late.

**Comment by gjcope** [comment]
Hi @ThibaultGuillaumont , thanks for the comment. Yes all aspects of the transform are involved in this bug.
